version: "2"

linters:
  default: none
  enable:
    - errcheck
    - godot
    - gosec
    - govet
    - ineffassign
    - makezero
    - prealloc
    - revive
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G104
        - G115
        - G602
    govet:
      enable-all: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - govet
        path: (.+)_test.go

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/leonhfr/orca)
  exclusions:
    generated: lax
