linters:
  enable:
    - errcheck
    - gci
    - godot
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/leonhfr/orca)
  govet:
    enable-all: true

issues:
  include:
    - EXC0005
    - EXC0012
    - EXC0014
    - EXC0015
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - govet
