builds:
  - id: orca
    goos:
      - linux
      - darwin
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
